// Auto-generated Gatsby GraphQL query types.
// These types are normally generated by `gatsby build` in `.cache/gatsby-types.d.ts`.
// This file provides the declarations needed for TypeScript type checking.

type MdxNode = {
  fields?: {
    slug?: string | null;
    entityType?: string | null;
  } | null;
  frontmatter?: Record<string, unknown> | null;
  parent?: Record<string, unknown> | null;
  excerpt?: string | null;
};

type AllMdxResult = {
  nodes: MdxNode[];
};

declare namespace Queries {
  type IndexPageQuery = {
    locations?: AllMdxResult | null;
    npcs?: AllMdxResult | null;
    sessions?: AllMdxResult | null;
    items?: AllMdxResult | null;
    lore?: AllMdxResult | null;
  };

  type ItemsPageQuery = {
    allMdx: AllMdxResult;
  };

  type LocationsPageQuery = {
    allMdx: AllMdxResult;
  };

  type LorePageQuery = {
    allMdx: AllMdxResult;
  };

  type NpcsPageQuery = {
    allMdx: AllMdxResult;
  };

  type SessionsPageQuery = {
    allMdx: AllMdxResult;
  };

  type CampaignDetailQuery = {
    mdx?: MdxNode | null;
  };

  type ItemDetailQuery = {
    mdx?: MdxNode | null;
  };

  type LocationDetailQuery = {
    mdx?: MdxNode | null;
  };

  type LoreDetailQuery = {
    mdx?: MdxNode | null;
  };

  type NpcDetailQuery = {
    mdx?: MdxNode | null;
  };

  type SessionDetailQuery = {
    mdx?: MdxNode | null;
  };
}
